abbr_dict = {
    # vietnam abbreviation 1
    "": "",
    "btc": "ban tổ chức",
    "htx": "Hợp tác xã",
    "ôb": "Ông bà",
    "tp": "Thành phố",
    "tư": "Trung ương",
    "ubnd": "Ủy ban nhân dân",
    "bch": "Ban Chấp hành",
    "chxhcnvn": "Cộng hòa Xã hội Chủ nghĩa Việt Nam",
    "mtdtgpmnvn": "Mặt trận Dân tộc Giải phóng miền Nam Việt Nam",
    "qđndvn": "Quân đội Nhân dân Việt Nam",
    "vnqdđ": "Việt Nam Quốc dân Đảng",
    "vndcch": "Việt Nam Dân chủ Cộng hòa",
    "lhq": "Liên Hiệp Quốc",
    "hđnd": "Hội đồng nhân dân",
    "nn&ptnt": 'Nông nghiệp và phát triển nông thôn',
    "ceo": "xi i âu",
    "bhxh": "bảo hiểm xã hội",
    "scandal": "sờ ken đồ",
    "nsut": "nghệ sĩ ưu tú",
    "stt": "số thứ tự",

    # vietnam abbreviation 2
    "chdc": "cộng hòa dân chủ",
    "chdcnd": "cộng hòa dân chủ nhân dân",
    "chlb": "cộng hòa liên bang",
    "chnd": "cộng hòa nhân dân",
    "ck": "chứng khoán",
    "clb": "câu lạc bộ",
    "cmnd": "chứng minh nhân dân",
    "cncn": "chi nhánh cấp nước",
    "cnh": "công nghiệp hóa",
    "cnkt": "công nhân kỹ thuật",
    "cnqsdđ": "chứng nhận quyền sử dụng đất",
    "cnsh": "công nghệ sinh học",
    "cntn": "cử nhân tài năng",
    "cntt": "công nghệ thông tin",
    "cnv": "công nhân viên",
    "cnvc": "công nhân viên chức",
    "cp": "cổ phần",
    "cph": "cổ phần hóa",
    "cpsxtm": "cổ phần xây dựng sản xuất thương mại",
    "cptd": "cổ phiếu tự do",
    "cpttt": "chậm phát triển trí tuệ",
    "cpxd": "cấp phép xây dựng",
    "cqđt": "cơ quan điều tra",
    "cscđ": "cảnh sát cơ động",
    "csdc": "cảnh sát dã chiến",
    "csdl": "cơ sở dữ liệu",
    "csđn": "cảnh sát đặc nhiệm",
    "csđt": "cơ sở đào tạo",
    "csđtlx": "cơ sở đào tạo lái xe",
    "csđttp": "cảnh sát điều tra tội phạm",
    "csđttpmt": "cảnh sát điều tra tội phạm ma túy",
    "csg": "cảng sài gòn",
    "csgt": "cảnh sát giao thông",
    "cshs": "cảnh sát hình sự",
    "cskh": "chăm sóc khách hàng",
    "cskt": "cảnh sát kinh tế",
    "cskv": "cảnh sát khu vực",
    "cspctpmt": "cục cảnh sát phòng chống tội phạm ma túy",
    "cspk": "công suất phản kháng",
    "csqlhc": "cảnh sát quản lý hành chính",
    "cssx": "cơ sở sản xuất",
    "csvc": "cơ sở vật chất",
    "csvn": "cộng sản việt nam",
    "csxh": "chính sách xã hội",
    "ct": "công ty",
    "ctcc": "công trình công cộng",
    "ctch": "chấn thương chỉnh hình",
    "ctck": "công ty chứng khoán",
    "ctclqg": "chương trình chống lao quốc gia",
    "ctcn": "công ty cấp nước",
    "ctcp": "công ty cổ phần",
    "ctđ": " chữ thập đỏ",
    "ctđl": "công ty điện lực",
    "ctsn": "chấn thương sọ não",
    "cttc": "cho thuê tài chính",
    "ctth": "chương trình truyền hình",
    "cttnhh": "công ty trách nhiệm hữu hạn",
    "cttt": "chương trình tiên tiến",
    "ctv": "cộng tác viên",
    "ctxh": "công tác xã hội",
    "cv": "chuyên viên",
    "cvpm": "công viên phần mềm",
    "cx": "cư xá",
    "dagtđt": "dự án giao thông đô thị",
    "đb": "đại biểu",
    "đbdt": "đồng bào dân tộc",
    "đbp": "điện biên phủ",
    "đbqh": "đại biểu quốc hội",
    "đbscl": "đồng bằng sông cửu long",
    "đbtn": "đại biểu thanh niên",
    "đbtsxb": "đánh bắt thủy sản xa bờ",
    "đc": "địa chỉ",
    "dcch": "dân chủ cộng hòa",
    "đcs": "đảng cộng sản",
    "đcstq": "đảng cộng sản trung quốc",
    "đcsvn": "đảng cộng sản việt nam",
    "dd": "dân dụng",
    "đd": "đại diện",
    "đđ": "động đất, đất đai",
    "ddvn": "duyên dáng việt nam",
    "đh": "đại học",
    "đhbc": "đại học bán công",
    "đhbk": "đại học bách khoa",
    "đhbkhcm": "đại học bách khoa thành phố hồ chí minh",
    "đhbkhn": "đại học bách khoa hà nội",
    "đhbktphcm": "đại học bách khoa thành phố hồ chí minh",
    "đhcđ": "đại học công đoàn",
    "đhclc": "đại học chất lượng cao",
    "đhcn": "đại học công nghệ",
    "đhct": "đại học cần thơ",
    "đhđcqt": "đại học đẳng cấp quốc tế",
    "đhđd": "đại học đông dương",
    "đhdl": "đại học dân lập",
    "đhđn": "đại học đà nẵng",
    "đhgtvt": "đại học giao thông vận tải",
    "đhhb": "đại học hồng bàng",
    "đhhvn": "đại học hàng hải việt nam",
    "đhkh": "đại học khoa học",
    "đhkhtn": "đại học khoa học tự nhiên",
    "đhkhtnhn": "đại học khoa học tự nhiên hà nội",
    "đhkhxh": "đại học khoa học xã hội",
    "đhkt": "đại học kỹ thuật",
    "dhktcn": "đại học kỹ thuật công nghệ",
    "đhktcn": "đại học kỹ thuật công nghệ",
    "đhktqd": "đại học kinh tế quốc dân",
    "đhn": "điện hạt nhân, đồng hồ nước",
    "đhnt": "đại học nha trang",
    "đhqg": "đại học quốc gia",
    "đhqghn": "đại học quốc gia hà nội",
    "dhs": "du học sinh",
    "đhsp": "đại học sư phạm",
    "đk": "đăng ký",
    "đkdt": "đăng ký dự thi",
    "đkđt": "điện kế điện tử",
    "đkhk": "đăng ký hộ khẩu",
    "đkkd": "đăng ký kinh doanh",
    "đkkh": "đăng ký kết hô",
    "đkvđ": "đương kim vô địch",
    "đkvn": "điền kinh việt nam",
    "đkxt": "đăng ký xét tuyển",
    "dl": "du lịch",
    "đl": "đo lường",
    "đltp": "điện kế điện tử",
    "đmn": "đá mỹ nghệ",
    "dn": "doanh nghiệp",
    "đn": "đồng nai, đà nẵng",
    "đna": "đông nam á",
    "đná": "đông nam á",
    "dnnn": "doanh nghiệp nhà nước",
    "dnt": "doanh nghiệp trẻ",
    "dntn": "doanh nghiệp tư nhân",
    "dnvn": "doanh nghiệp việt nam",
    "dnvvn": "doanh nghiệp vừa và nhỏ",
    "đrl": "điểm rèn luyện",
    "ds": "dân s",
    "đs": "đường sắt",
    "đsq": "đại sứ quán",
    "dt": "dự tuyển",
    "đt": "đào tạo",
    "đtb": "điểm trung bình",
    "đtđ": "đái tháo đường",
    "đtdđ": "điện thoại di động",
    "dtht": "dạy thêm học thêm",
    "đthvn": "đài truyền hình việt nam",
    "đtla": "đồng tính luyến ái",
    "đtlt": "đào tạo liên thông",
    "đtnn": "đầu tư nước ngoài",
    "dtqg": "đội tuyển quốc gia",
    "đtqg": "đội tuyển quốc gia",
    "đttx": "đào tạo từ xa",
    "đtv": "điều tra viên",
    "đtvhd": "động thực vật hoang dã",
    "đtvn": "đội tuyển việt nam",
    "đtxdcb": "đầu tư xây dựng cơ bả",
    "dv": "dịch vụ, diễn viên",
    "đv": "đoàn viên",
    "đvht": "đơn vị học trình",
    "dvtmcm": "dịch vụ thương mại cà mau",
    "đvtn": "đoàn viên thanh niên",
    "dvtt": "dịch vụ trực tuyến",
    "đvttn": "đoàn viên thanh thiếu nhi",
    "đvưt": "đoàn viên ưu tú",
    "dvvl": "dịch vụ việc làm",
    "eu": "liên minh châu âu",
    "evn": "công ty viễn thông điện lực",
    "fifa": "liên đoàn bóng đá thế giới",
    "gcmnd": "giấy chứng minh nhân dân",
    "gcn": "giấy chứng nhận",
    "gcnđkkd": "giấy chứng nhận đăng ký kinh doanh",
    "gcnkqt": "giấy chứng nhận kết quả thi",
    "gcnqsd": "giấy chứng nhận quyền sử dụng",
    "gcnqsdđ": "giấy chứng nhận quyền sử dụng đất",
    "gcnqsdđơ": "giấy chứng nhận quyền sử dụng đất ở",
    "gcnqsh": "giấy chứng nhận quyền sở hữu",
    "gcnqshn": "giấy chứng nhận quyền sở hữu nhà",
    "gcnqshnơ": "giấy chứng nhận quyền sở hữu nhà ở",
    "gcnsk": "giấy chứng nhận sức khỏe",
    "gcq": "giấy chủ quyền",
    "gd": "giáo dục",
    "gđ": "giám đốc",
    "gdđh": "giáo dục dục đại học",
    "gđđh": "giám đốc điều hành",
    "gdđt": "giáo dục và đào tạo",
    "gdgt": "giáo dục giới tính",
    "gdnn": "giáo dục nghề nghiệp",
    "gđt": "gạch đồng tâm",
    "gđtt": "giám đốc thông tin",
    "gdtx": "giáo dục thường xuyên",
    "ghpgvn": "giáo hội phật giáo việt nam",
    "gk": "giáo khoa",
    "gkqt": "chứng nhận kết quả thi",
    "gl": "gia lai",
    "gp": "giấy phép",
    "gpc": "công ty dịch vụ viễn thông",
    "gplhđb": "giấy phép lưu hành đặc biệt",
    "gplx": "giấy phép lái xe",
    "gpnk": "phép nhập khẩu",
    "gptm": "giải phẫu thẩm mỹ",
    "gpxd": "giấy phép xây dựng",
    "gs": "giáo sư",
    "gsts": "giáo sư tiến sỹ",
    "gstskh": "giáo sư tiến sỹ khoa học",
    "gstt": "giám sát trọng tài",
    "gt": "giá trị",
    "gtcc": "giao thông công chánh",
    "gtgt": "giá trị gia tăng",
    "gtmt": "giãn tĩnh mạch tinh",
    "gtvt": "giao thông vận tải",
    "gv": "giáo viên, giảng viên",
    "gvcn": "giáo viên chủ nhiệm",
    "gvg": "giáo viên giỏi",
    "gvmn": "giáo viên mầm non",
    "gvth": "giáo viên tiểu học",
    "gvtn": "giáo viên tình nguyện",
    "hagl": "hoàng anh gia lai",
    "hb": "học bổng",
    "hc": "hành chính",
    "hcb": "huy chương bạc",
    "hcđ": "huy chương đồng",
    "hcm": "hồ chí minh",
    "hctc": "học chế tín chỉ",
    "hctl": "hội chợ triển lăm",
    "hcv": "huy chương vàng",
    "hcvl": "hội chợ việc làm",
    "hd": "hướng dẫn",
    "hđ": "hội đồng",
    "hđba": "hội đồng bảo an liên hiệp quốc",
    "hđcd": "hội đồng chức danh",
    "hđcdgs": "hội đồng chức danh giáo sư",
    "hđcdgscs": "hội đồng chức danh giáo sư cơ sở",
    "hđcdgsn": "hội đồng chức danh giáo sư ngành",
    "hđcdgsnn": "hội đồng chức danh giáo sư nhà nước",
    "hđct": "hội đồng coi thi",
    "hđđb": "hội đồng đền bù",
    "hđđg": "hội đồng định giá",
    "hđh": "hệ điều hành",
    "hđkt": "hợp đồng kinh tế",
    "hđlđ": "hợp đồng lao động",
    "hđndtp": "hội đồng nhân dân thành phố",
    "hđnt": "hội đồng nghệ thuật",
    "hđqt": "hội đồng quản trị",
    "hđt": "hội đồng trường , hội đồng thi",
    "hđtđ": "hội đồng thẩm định",
    "hđts": "hội đồng tuyển sinh",
    "hđtt": "hội đồng trọng tài",
    "hdv": "hướng dẫn viên",
    "hđxx": "hội đồng xét xử",
    "hh": "hoa hậu",
    "hhtg": "hoa hậu thế giới",
    "hhvn": "hoa hậu việt nam",
    "hk": "học kỳ",
    "hkdd": "hàng không dân dụng",
    "hkddvn": "hàng không dân dụng việt nam",
    "hkhkt": "hội khoa học kỹ thuật",
    "hkhktvn": "hội khoa học kỹ thuật việt nam",
    "hktt": "hộ khẩu thường trú",
    "hl": "huấn luyện",
    "hlbđ": "hoa lâm bình định",
    "hlqg": "huấn luyện quốc gia",
    "hlttqg": "trung tâm huấn luyện thể thao quốc gia",
    "hlv": "huấn luyện viên",
    "hmnđ": "hiến máu nhân đạo",
    "hn": "hội nghị",
    "hnd": "hội nông dân",
    "hngđ": "hôn nhân gia đình",
    "hnht": "hội nghị hiệp thương",
    "hnv": "hội nhà văn",
    "hp": "học phần",
    "hq": "hải quan",
    "hqđt": "hải quan điện tử",
    "hqhp": "hải quan hải phòng",
    "hs": "học sinh",
    "hsbc": "học sinh bán công",
    "hsđkdt": "hồ sơ đăng ký dự thi",
    "hsg": "học sinh giỏi",
    "hsgqg": "học sinh giỏi quốc gia",
    "hsgqt": "học sinh giỏi quốc tế",
    "hspt": "học sinh phổ thông",
    "hssv": "học sinh sinh viên",
    "hsv": "hội sinh viên",
    "htcđ": "học tập cộng đồng",
    "htxdvnn": "hợp tác xã dịch vụ nông nghiệp",
    "hv": " học viên",
    "hvannd": "học viện an ninh nhân dân",
    "hvbcvt": "học viện bưu chính viễn thông",
    "hvch": "học viên cao học",
    "hvcnbcvt": "học viện công nghệ bưu chính viễn thông",
    "hvkhqs": "học viện khoa học quân sự",
    "hvn": "honda việt nam",
    "hvncl": "hàng việt nam chất lượng",
    "hvnclc": "hàng việt nam chất lượng cao",
    "hvnh": "học viện ngân hàng",
    "kbnn": "kho bạc nhà nước",
    "kcb": "khám chữa bệnh",
    "kcn": "khu công nghiệp",
    "kcx": "khu chế xuất",
    "kdc": "khu dân cư",
    "kđcl": "kiểm định chất lượng",
    "kđclgd": "kiểm định chất lượng giáo dục",
    "kdcn": "kiểu dáng công nghiệp",
    "kddv": "kinh doanh dịch vụ",
    "kdđv": "kiểm dịch động vật",
    "kdhđc": "kinh doanh hàng đa cấp",
    "kdl": "khu du lịch",
    "kdn": "kinh doanh nhà",
    "kdnpn": "kinh doanh nhà phú nhuận",
    "kđs": "khu đường sông",
    "kđt": "khu đô thị",
    "kđtm": "khu đô thị mới",
    "kh": "kế hoạch",
    "khcn": "khoa học công nghệ",
    "khđt": "kế hoạch đầu tư",
    "khkd": "kế hoạch kinh doanh",
    "khkt": "khoa học kỹ thuật",
    "khkthn": "khoa học kỹ thuật hạt nhân",
    "khkths": "khoa học kỹ thuật hình sự",
    "khktnn": "khoa học kỹ thuật nông nghiệp",
    "khktnnmn": "khoa học kỹ thuật nông nghiệp miền nam",
    "khls": "khoa học lịch sử",
    "khtn": "khoa học tự nhiên",
    "khxh": "khoa học xãn hội",
    "kk": "khuyến khíc",
    "kkt": "khu kinh tế",
    "kl": "kết luận",
    "klđt": "kết luận điều tra",
    "klqg": "kỷ lục quốc gia",
    "kn": "khuyến nông",
    "kntc": "khiếu nại tố cáo",
    "kp": "khu phố",
    "ks": "kỹ sư, khách sạn",
    "ksnd": "kiểm sát nhân dân",
    "ksndtc": "kiểm sát nhân dân tối cao",
    "kst": "ký sinh trùng",
    "ksv": "kiểm sát viên",
    "ktm": "khu thương mại",
    "ktnn": "kinh tế nhà nước",
    "ktqd": "kinh tế quốc dân",
    "ktqdhn": "kinh tế quốc dân hà nội",
    "kts": "kiến trúc sư",
    "kttv": "khí tượng thủy văn",
    "ktv": "kỹ thuật viên",
    "ktx": "ký túc xá",
    "kv": "khu vực",
    "kv1": "khu vực một",
    "kv2": "khu vực hai",
    "kv3": "khu vực ba",
    "lb": "liên bang",
    "lđ": "lao động",
    "lđbđ": "liên đoàn bóng đá",
    "lđbđvn": "liên đoàn bóng đá việt nam",
    "lđlđ": "liên đoàn lao động",
    "ldp": "đảng dân chủ tự do",
    "lđtb": "lao động thương binh",
    "lđtbxh": "lao động thương binh xã hội",
    "lh": "liên hiệp",
    "lhp": "liên hoan phim",
    "lhpn": "liên hiệp phụ nữ",
    "lhs": "lưu học sinh",
    "lhtn": "liên hiệp thanh niên",
    "lhtnvn": "hội liên hiệp thanh niên việt nam",
    "ll": "lực lượng",
    "lllđ": "lực lượng lao động",
    "ls": "luật sư",
    "lsq": "lãnh sự quán",
    "ltqđtd": "lây truyền qua đường tình dục",
    "mbh": "mũ bảo hiểm",
    "mhx": "mùa hè xanh",
    "ms": "mã số",
    "mt": "môi trường",
    "mtđt": "máy tính điện tử",
    "mttq": "mặt trận tổ quốc",
    "mttqvn": "mặt trận tổ quốc việt nam",
    "mtxt": "máy tính xách tay",
    "nc": "nghiên cứu",
    "ncc": "nhà cung cấp",
    "nckh": "nghiên cứu khoa học",
    "ncl": "ngoài công lập",
    "ncs": "nghiên cứu sinh",
    "nctt": "nghiên cứu thị trường",
    "nd": "nhân dân",
    "nđ": "nghị định",
    "ndt": "nhân dân tệ",
    "nđt": "nhà đầu tư",
    "nh": "ngân hàng",
    "nhcsxh": "ngân hàng chính sách xã hội",
    "nhctcn": "ngân hàng công thương chi nhánh",
    "nhcthp": "ngân hàng công thương hải phòng",
    "nhctvn": "ngân hàng công thương việt nam",
    "nhđa": "ngân hàng đông á",
    "nhđt": "ngân hàng đầu tư",
    "nhđtpt": "ngân hàng đầu tư phát triển",
    "nhnn": "ngân hàng nhà nước",
    "nhnnptnt": "ngân hàng nông nghiệp và phát triển nông thôn",
    "nhnnvn": "ngân hàng nhà nước việt nam",
    "nhnt": "ngân hàng ngoại thương",
    "nhtm": "ngân hàng thương mại",
    "nhtmcp": "ngân hàng thương mại cổ phần",
    "nhtmnn": "ngân hàng thương mại nhà nước",
    "nhtmqd": "ngân hàng thương mại quốc doanh",
    "nhtq": "ngân hàng trung ương trung quốc",
    "nhtsa": "cục an toàn xa lộ quốc gia mỹ",
    "nhtư": "ngân hàng trung ương",
    "nhtw": "ngân hàng trung ương",
    "nk": "nhập khẩu",
    "nkbv": "nhiễm khuẩn bệnh viện",
    "nknv": "năng khiếu nghiệp vụ",
    "nkt": "người khuyết tật",
    "nl": "năng lượng",
    "nlđ": "người lao động",
    "nlmt": "năng lượng mặt trời",
    "nls": "nông lâm sản",
    "nltt": "năng lượng tái tạo",
    "nmđ": "nhà máy điện",
    "nn": "nhà nước",
    "nncđdc": "nạn nhân chất độc da cam",
    "nnptnt": "nông nghiệp và phát triển nông thôn",
    "npp": "nhà phân phối",
    "nq": "nghị quyết",
    "nqd": "ngoài quốc doanh",
    "ns": "nghệ sỹ",
    "nsnd": "nghệ sỹ nhân dân",
    "nsnn": "ngân sách nhà nước",
    "nst": "nhiễm sắc thể",
    "nsưt": "nghệ sỹ ưu tú",
    "ntbd": "nghệ thuật biểu diễn",
    "ntd": "nhà tuyển dụng",
    "ntk": "nhà thiết kế",
    "nv": "nhân viên",
    "nv1": "nguyện vọng một",
    "nv2": "nguyện vọng hai",
    "nv3": "nguyện vọng ba",
    "nvh": "nhà văn hóa",
    "nvhtn": "nhà văn hóa thanh niên",
    "nxb": "nhà xuất bản",
    "nxbgd": "nhà xuất bản giáo dục",
    "nxbkhxh": "nhà xuất bản khoa học xã hội",
    "nxbqđnd": "nhà xuất bản quân đội nhân dân",
    "nxbtn": "nhà xuất bản tự nhiên",
    "nxbvhtt": "nhà xuất bản văn hóa nghệ thuật",
    "pcbl": "phòng chống bão lụt",
    "pcbltkcn": "phòng chống bão lụt và tìm kiếm cứu nạn",
    "pcbth": "phổ cập bậc trung học",
    "pcc": "phòng công chứng",
    "pccc": "phòng cháy chửa cháy",
    "pcgd": "phổ cập giáo dục",
    "pcgdbth": "phổ cập giáo dục bậc trung học",
    "pcgdth": "phổ cập giáo dục tiểu học",
    "pcgdthcs": "phổ cập giáo dục trung học cơ sở",
    "pclbmn": "phòng chống lụt bão miền nam",
    "pclbtư": "phòng chống lụt bão trung ương",
    "pclbtw": "phòng chống lụt bão trung ương",
    "pct": "phó chủ tịch",
    "pcth": "phổ cập tiểu học",
    "pcthcs": "phổ cập trung học cơ sở",
    "pctn": "phòng chống tệ nạn",
    "pctnxh": "phòng chống tệ nạn xã hội",
    "pctpcnc": "phòng chống tội phạm công nghệ cao",
    "pgđ": "phó giám đốc",
    "pgs": "phó giáo sư",
    "phhs": "phụ huynh học sinh",
    "pl": "pháp luật",
    "pm": "phần mềm",
    "pn": "phụ nữ",
    "pp": "phương pháp",
    "ps": "phóng sự",
    "ptcs": "phổ thông cơ sở",
    "ptn": "phòng thí nghiệm",
    "ptnt": "phát triển nông thôn",
    "ptt": "phó thủ tướng",
    "ptth": "phổ thông trung học",
    "pttm": "phẫu thuật thẩm mỹ",
    "ptv": "phát thanh viên",
    "pv": "phóng viên",
    "qbltd": "quĩ bảo lãnh tín dụng",
    "qc": "quy chế",
    "qcdccs": "quy chế dân chủ cơ sở",
    "qcgnhh": "quy chế ghi nhãn hàng hóa",
    "qchq": "quan chức hải quan",
    "qckdtxd": "quy chế kinh doanh thép xây dựng",
    "qckt": "quy chuẩn kĩ thuật",
    "qđ": "quyết định",
    "qđnd": "quân đội nhân dân",
    "qg": "quốc gia",
    "qh": "quốc hội",
    "qhtd": "quan hệ tình dục",
    "qk": "quân khu",
    "ql": "quản lý",
    "qld": "quản lý dược",
    "qlda": "quản lý dự án",
    "qlđt": "quản lý đào tạo",
    "qltt": "quản lý thị trường",
    "qsd": "quyền sử dụng",
    "qsdđ": "quyền sử dụng đất",
    "qtkd": "quản trị kinh doanh",
    "sbd": "số báo danh",
    "sd": "sử dụng",
    "sdđ": "sử dụng đất",
    "sdđnn": "sử dụng đất nông nghiệp",
    "sđh": "sau đại học",
    "sđk": "số đăng ký",
    "sđt": "số điện thoại",
    "sgd": "sở giáo dục",
    "sgk": "sách giáo khoa",
    "sgtvt": "sở giao thông vận tải",
    "sh": "sinh hoạt",
    "shnn": "sở hữu nhà nước",
    "shtd": "sinh hoạt tình dục",
    "shtt": "sở hữu trí tuệ",
    "sk": "sân khấu",
    "skhcn": "sở khoa học công nghệ",
    "skhcnmt": "sở khoa học công nghệ và môi trường",
    "skhđt": "sở kế hoạch và đầu tư",
    "skss": "sức khỏe sinh sản",
    "sn": "sinh năm, sinh ngày",
    "snn": "sở nông nghiệp",
    "sp": "sản phẩm",
    "spkt": "sư phạm kỹ thuật",
    "ss": "sĩ số",
    "sv": "sinh viên",
    "svđ": "sân vận động",
    "svhs": "sinh viên học sinh",
    "sv–hs": "sinh viên học sinh",
    "svnckh": "sinh viên nghiên cứu khoa học",
    "svtn": "sinh viên tình nguyện",
    "svvn": "sinh viên việt nam",
    "sx": "sản xuất",
    "sxh": "sốt xuất huyết",
    "syll": "sơ yếu lý lịch",
    "tacn": "thức ăn chăn nuôi",
    "tand": "tòa án nhân dân",
    "tandtc": "tòa án nhân dân tối ca",
    "tbd": "thái bình dương",
    "tbktsg": "thời báo kinh tế sài gòn",
    "tbktvn": "thời báo kinh tế việt nam",
    "tbmmn": "tai biến mạch máu não",
    "tbt": "tổng biên tập",
    "tbtt": "thuê bao trả trước",
    "tbxh": "thương binh xã hội",
    "tc": "tài chính, tổng cộng",
    "tcbvntd": "tiêu chuẩn và bảo vệ người tiêu dùng",
    "tccn": "trung cấp chuyên nghiệp",
    "tccs": "tổ chức cơ sở",
    "tchq": "tổng cục hải quan",
    "tckh": "tài chính - kế hoạch",
    "tckt": "tài chính - kế toán",
    "tcmn": "thủ công mỹ nghệ",
    "tcmr": "tiêm chủng mở rộng",
    "tcn": "trung cấp nghề",
    "tcnn": "tài chính nhà nước",
    "tcs": "trịnh công sơn",
    "tct": "tổng công ty",
    "tctd": "tổ chức tín dụng",
    "tctt": "trò chơi trực tuyến",
    "tcttmsg": "tổng công ty thương mại sài gòn",
    "tcvn": "tiêu chuẩn việt nam",
    "tcvsg": "thảo cầm viên sài gòn",
    "td": "tình dục",
    "tđ": "từ điển",
    "tđbkvn": "từ điển bách khoa việt nam",
    "tđc": "tái định cư",
    "tdtt": "thể dục thể thao",
    "tdttqg": "thể dục thể thao quốc gia",
    "tdv": "trình dược viên",
    "tfs": "hãng phim truyền hình tphcm",
    "tg": "thế giới",
    "tgđ": "tổng giám đốc",
    "tgpl": "trợ giúp pháp lý",
    "th": "tiểu học",
    "thcb": "trung học chuyên ban",
    "thcn": "trung học chuyên nghiệp",
    "thcs": "trung học cơ sở",
    "thcsnd": "thực hiện chính sách nhà đất",
    "thcsnđ": "thực hiện chính sách nhà đất",
    "thdl": "trung học dân lập",
    "thgt": "tín hiệu giao thông",
    "thkts": "truyền hình kỹ thuật số",
    "thktsmđ": "truyền hình kỹ thuật số mặt đất",
    "thpt": "trung học phổ thông",
    "thqg": "thương hiệu quốc gia",
    "ths": "tín hiệu số",
    "thtt": "truyền hình trực tiếp",
    "thvn": "truyền hình việt nam",
    "thx": "tân hoa xã",
    "tk": "thiết kế",
    "tkcn": "tìm kiếm cứu nạn",
    "tm": "thương mại",
    "tmcp": "thương mại cổ phần",
    "tmđt": "thương mại điện tử",
    "tn": "thanh niên",
    "tncn": "thu nhập cá nhân",
    "tncs": "thanh niên cộng sản",
    "tnđh": "tốt nghiệp đại học",
    "tndn": "thu nhập doanh nghiệp",
    "tnđt": "thoát nước đô thị",
    "tngt": "tai nạn giao thông",
    "tnhh": "trách nhiệm hữu hạn",
    "tnk": "thuế nhập khẩu",
    "tnkq": "trắc nghiệm khách quan",
    "tnln": "thanh niên lập nghiệp",
    "tnmt": "tài nguyên môi trường",
    "tnnd": "tiếng nói nhân dân",
    "tnnt": "thanh niên nông thôn",
    "tno": "thanh niên online",
    "tns": "tu nghiệp sinh",
    "tnsv": "thanh niên sinh viên",
    "tnsvvn": "thanh niên sinh viên việt nam",
    "tnt": "tình nguyện trẻ",
    "tntn": "tài nguyên thiên nhiên",
    "tntp": "thiếu niên tiền phong",
    "tnv": "tình nguyện viên",
    "tnvn": "thanh niên việt nam",
    "tnxh": "tệ nạn xã hội",
    "tnxk": "thanh niên xung kích",
    "tnxp": "thanh niên xung phong",
    "tpcđ": "trái phiếu chuyển đổi",
    "tpcn": "thực phẩm chức năng",
    "tphcm": "thành phố hồ chí minh",
    "tq": "trung quốc",
    "tsdđ": "tiền sử dụng đất",
    "tskh": "tiến sỹ khoa học",
    "tsn": " tân sơn nhất",
    "tt": "trung tâm",
    "ttbđs": "thị trường bất động sản",
    "ttbdvh": "trung tâm bồi dưỡng văn hóa",
    "ttbdvhng": "trung tâm bồi dưỡng văn hóa ngoài giờ",
    "ttbvqtg": "trung tâm bảo vệ quyền tác giả",
    "ttbyt": "trang thiết bị y tế",
    "ttck": "thị trường chứng khoán",
    "ttcn": "tiểu thủ công nghiệp",
    "ttcp": "thủ tướng chính phủ",
    "ttdd": "trung tâm dinh dưỡng",
    "ttđm": "trung tâm điện máy",
    "ttdv": "trung tâm dịch vụ",
    "ttdvvl": "trung tâm dịch vụ việc làm",
    "ttg": "thủ tướng",
    "ttgdck": "trung tâm giao dich chứng khoán",
    "ttgdtx": "trung tâm giáo dục thường xuyên",
    "ttgt": "trật tự giao thông",
    "tthtcđ": "trung tâm học tập cộng đồng",
    "tthtsv": "trung tâm hỗ trợ sinh viên",
    "ttk": "tổng thư ký",
    "ttlt": "thông tư liên tịch",
    "ttn": "thanh thiếu niên",
    "ttnn": "trung tâm ngoại ngữ",
    "ttqlkt": "trật tự quản lý kinh tế",
    "ttth": "trung tâm tin học",
    "tttm": "trung tâm thương mại",
    "ttton": "thụ tinh trong ống nghiệm",
    "ttttn": "trí thức trẻ tình nguyện",
    "ttvgt": "trật tự viên giao thông",
    "ttvh": "trung tâm văn hóa",
    "ttvn": "thể thao việt nam",
    "ttxh": "trật tự xã hội",
    "ttxvn": "thông tấn xã việt nam",
    "ttyt": "trung tâm y tế",
    "ttytdp": "trung tâm y tế dự phòng",
    "tv": "ti vi",
    "tvhk": "tiếp viên hàng không",
    "tvn": "than việt nam",
    "tvqh": "thường vụ quốc hội",
    "tvv": "tư vấn viên",
    "tw": "trung ương",
    "tx": "thị xã",
    "ubcknn": "ủy ban chứng khoán nhà nước",
    "ubkt": "uỷ ban kiểm tra",
    "ubmttq": "ủy ban mạt trận tổ quốc",
    "ubmttqvn": "ủy ban mặt trận tổ quốc việt nam",
    "ubndtp": "ủy ban nhân dan thành phố",
    "ubtdtt": "ủy ban thể dục thể thao",
    "ubtvqh": "ủy ban thường vụ quốc hội",
    "ưcv": "ứng cử viên",
    "ut": "ung thư",
    "uv": "ủy viên",
    "uvbch": "ủy viên ban chấp hành",
    "uvbct": "ủy viên bộ chính trị",
    "vck": "vòng chung kết",
    "vd": "ví dụ",
    "vđ": "vô địch",
    "vđqg": "vô địch quốc gia",
    "vđv": "vận động viên",
    "vđvqg": "vận động viên quốc gia",
    "vh": "văn hóa",
    "vhgdtntn": "văn hóa giáo dục thanh niên thiếu niên",
    "vhgdttnnđ": "văn hóa giáo dục thanh thiếu niên và nhi đồng",
    "vhnt": "văn học nghệ thuật",
    "vhtt": "văn hóa thông tin",
    "vks": "viện kiểm sát",
    "vksnd": "viện kiểm sát nhân dân",
    "vksndtc": "viện kiểm sát nhân dân tối cao",
    "vl": "vật lý",
    "vltk": "võ lâm truyền kỳ",
    "vlxd": "vật liệu xây dựng",
    "vn": "việt nam",
    "vp": "văn phòng",
    "vpcp": "văn phòng chính phủ",
    "vpđd": "văn phòng đại diện",
    "vqg": "vườn quốc gia",
    "vs": "vệ sinh",
    "vt": "viên thông",
    "vtv": "đài truyền hình việt nam",
    "xd": "xây dựng",
    "xdcb": "xây dựng cơ bản",
    "xđgn": "xoá đói giảm nghèo",
    "xdhk": "xăng dầu hàng không",
    "xh": "xã hội",
    "xhcn": "xã hội chủ nghĩa",
    "xhh": "xã hội hóa",
    "xk": "xuất khẩu",
    "xklđ": "xuất khẩu lao động",
    "xn": "xí nghiệp",
    "xnk": "xuất nhập khẩu",
    "xskt": "xổ số kiến thiết",
    "xttm": "xúc tiến thương mại",
    "xx": "xét xử",
    "ykvn": "y khoa việt nam",
    "ytdp": "y tế dự phòng",
    "yt": "y tế",


    # english word
    "covid": "cô vít",
    "olympic": "ô lim pích",
    "code": "cốt",

    # english abbreviation
    "usd": "u ét đê",
    "url": "u rờ lờ",
    "qr": "quy a",
    "imf": "ai em ép",

    # sign
    "%": "phần trăm",
    "+": "cộng",
    "-": "trừ",
    "*": "nhân",
    "/": "chia",
    "$": "đô la",
    "@": "a còng",

    # unit
    "kg": "ki lô gam",
    "đ": "đồng",

    # english alphabet
    "a": "ây",
    "b": "bi",
    "c": "xi",
    "d": "đi",
    "e": "i",
    "f": "ép",
    "g": "di",
    "h": "ết",
    "i": "ai",
    "j": "dây",
    "k": "cây",
    "l": "eo",
    "m": "em",
    "n": "en",
    "o": "âu",
    "p": "pi",
    "q": "kiu",
    "r": "a",
    "s": "ét",
    "t": "ti",
    "u": "iu",
    "v": "vi",
    "w": "đắp liu",
    "x": "ích",
    "y": "goai",
    "z": "dét",


    # english name
    "indonesia": "in đô nê xi a",
    "afghanistan": "áp ga nít xơ tan",
    "argentina": "ác hen ti na",
    "armenia": "ác mê ni a",
    "australia": "ốt xơ trây li a",
    "austria": "áo",
    "belgium":  "bỉ",
    "brazil": "bờ ra xin",
    "bulgaria": "bun ga ri",
    "campuchia": "cam pu chia",
    "canada": "ca na đa",
    "chad": "sát",
    "chile": "chi lê",
    "cuba": "cu ba",
    "iran": "i ran",
    "iraq": "i rắc",
    "ireland": "ai len",
    "israel": "ít xa ren",
    "italy":  "i ta li a",
    "malaysia": "ma lai xi a",
    "mexico": "mê xi cô",
    "myanmar": "mi an ma",
    "mongolia":"mông cổ",
    "netherlands": "hà lan",
    "norway": "na uy",
    "pakistan": "pa kít xơ tan",
    "bangladesh": "băng la đét",
    "philippines": "phi líp pin",
    "poland": "ba lan",
    "portugal": "bồ đào nha",
    "romania": "ru ma ni",
    "russia": "liên bang nga",
    "singapore": "xin ga po",
    "spain": "tây ban nha",
    "sri-lanka": "sờ ri lan ka",
    "sudan": "xu đăng",
    "sweden": "thụy điển",
    "switzerland": "thụy sĩ",
    "thailand": "thái lan",
    "turkey": "thổ nhĩ kỳ",
    "taiwan": "đài loan",
    "ukraine":   "u cờ rai na",
    "usa": "mỹ",
    "uruguay": "u ru guay",
    "vatican": "va ti căng",
    "vanuatu": "va nu a tu",
    "vietnam":  "việt nam",

}


def check_abbr(str):
    try:
        res_str = abbr_dict[str.lower()]
        return res_str
    except KeyError:
        pass
    return ''


